import MarkdownIt from "markdown-it";
import anchor from "markdown-it-anchor";
import container from "markdown-it-container";
import footnote from "markdown-it-footnote";
import taskLists from "markdown-it-task-lists";
import texmath from "markdown-it-texmath";
import katex from "katex";
import hljs from "highlight.js";
import DOMPurify from "dompurify";

const escapeHTML = (value) => value
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

const slugCounts = new Map();
const slugify = (value) => {
  const base = value.toLowerCase().trim()
    .normalize("NFKD").replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\p{Letter}\p{Number}]+/gu, "-").replace(/^-|-$/g, "") || "section";
  const count = slugCounts.get(base) || 0;
  slugCounts.set(base, count + 1);
  return count ? `${base}-${count}` : base;
};

const md = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
  breaks: false,
  highlight(code, language) {
    const valid = language && hljs.getLanguage(language);
    const highlighted = valid ? hljs.highlight(code, { language }).value : hljs.highlightAuto(code).value;
    const label = valid ? language : "code";
    return `<pre class="code-block"><span class="code-language">${escapeHTML(label)}</span><button class="copy-code" type="button">Copy</button><code class="hljs language-${escapeHTML(label)}">${highlighted}</code></pre>`;
  }
});

md.use(anchor, { slugify, permalink: false });
md.use(footnote);
md.use(taskLists, { enabled: false, label: true, labelAfter: true });
md.use(texmath, { engine: katex, delimiters: "dollars", katexOptions: { throwOnError: false, strict: "ignore" } });

for (const kind of ["note", "tip", "important", "warning", "caution"]) {
  md.use(container, kind, {
    validate: (params) => params.trim().toLowerCase().startsWith(kind),
    render(tokens, index) {
      if (tokens[index].nesting === 1) {
        const supplied = tokens[index].info.trim().slice(kind.length).trim();
        const title = supplied || kind[0].toUpperCase() + kind.slice(1);
        return `<aside class="callout callout-${kind}" role="note"><div class="callout-title">${escapeHTML(title)}</div>`;
      }
      return "</aside>";
    }
  });
}

const defaultFence = md.renderer.rules.fence;
md.renderer.rules.fence = (tokens, index, options, env, self) => {
  const token = tokens[index];
  if (token.info.trim().toLowerCase() === "mermaid") {
    return `<pre class="mermaid">${escapeHTML(token.content)}</pre>`;
  }
  return defaultFence(tokens, index, options, env, self);
};

const state = {
  headingID: null,
  progress: 0,
  verticalOffset: 0,
  wordCount: 0,
  activeSearchIndex: -1,
  searchCount: 0,
  activeSearchSection: "",
  linkDestination: null,
  selectedText: ""
};

const root = document.querySelector("#document-root");
const bootstrap = window.__MD22_BOOTSTRAP__;
const normalizeCallouts = (markdown) => markdown.replace(
  /^>\s*\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*([^\n]*)\n((?:>[^\n]*(?:\n|$))*)/gim,
  (_, rawKind, title, body) => {
    const kind = rawKind.toLowerCase();
    const content = body.replace(/^>\s?/gm, "");
    return `::: ${kind}${title ? ` ${title.trim()}` : ""}\n${content}\n:::\n`;
  }
);
slugCounts.clear();
const dirtyHTML = md.render(normalizeCallouts(bootstrap.markdown));
root.innerHTML = DOMPurify.sanitize(dirtyHTML, {
  USE_PROFILES: { html: true },
  ADD_ATTR: ["class", "id", "target", "rel", "aria-label", "checked", "disabled"],
  FORBID_TAGS: ["script", "style", "iframe", "object", "embed", "form", "button"],
  FORBID_ATTR: ["style", "srcset"]
});

// Controls below are generated by MD22 after untrusted author HTML is sanitized.
root.querySelectorAll("pre.code-block").forEach((block) => {
  const code = block.querySelector("code");
  const button = document.createElement("button");
  button.type = "button";
  button.className = "copy-code";
  button.textContent = "Copy";
  button.setAttribute("aria-label", "Copy code");
  button.addEventListener("click", async () => {
    await navigator.clipboard.writeText(code?.textContent || "");
    button.textContent = "Copied";
    setTimeout(() => { button.textContent = "Copy"; }, 1200);
  });
  block.prepend(button);
});

root.querySelectorAll("input.task-list-item-checkbox").forEach((checkbox) => {
  checkbox.disabled = true;
  checkbox.setAttribute("aria-label", checkbox.checked ? "Completed task" : "Incomplete task");
});

root.querySelectorAll("a[href]").forEach((link) => {
  const href = link.getAttribute("href");
  if ((bootstrap.missingReferences || []).includes(href)) {
    link.classList.add("broken-link");
    link.setAttribute("aria-label", `${link.textContent}, unavailable link to ${href}`);
    link.title = `Unavailable: ${href}`;
  }
  if (/^https?:/i.test(href)) {
    link.classList.add("external-link");
    link.setAttribute("rel", "noopener noreferrer");
  }
  link.addEventListener("mouseenter", () => { state.linkDestination = href; });
  link.addEventListener("mouseleave", () => { state.linkDestination = null; });
  link.addEventListener("focus", () => { state.linkDestination = href; });
  link.addEventListener("blur", () => { state.linkDestination = null; });
});

root.querySelectorAll("img").forEach((image) => {
  image.addEventListener("error", () => {
    const placeholder = document.createElement("span");
    placeholder.className = "missing-resource";
    placeholder.setAttribute("role", "img");
    placeholder.setAttribute("aria-label", `Missing image: ${image.getAttribute("src") || "unknown"}`);
    placeholder.textContent = `◫ Missing image — ${image.getAttribute("src") || "unknown"}`;
    image.replaceWith(placeholder);
  }, { once: true });
});

root.querySelectorAll("table, pre.mermaid, .katex-display").forEach((element) => {
  if (element.parentElement?.classList.contains("wide-lane")) return;
  const lane = document.createElement("div");
  lane.className = "wide-lane";
  element.replaceWith(lane);
  lane.append(element);
});

const headings = [...root.querySelectorAll("h1, h2, h3, h4, h5, h6")];
headings.forEach((heading) => {
  heading.dataset.title = heading.textContent;
  const action = document.createElement("a");
  action.className = "bookmark-heading";
  action.href = `md22-action://bookmark?heading=${encodeURIComponent(heading.id)}`;
  action.textContent = "☆";
  action.title = `Bookmark ${heading.textContent}`;
  action.setAttribute("aria-label", `Bookmark heading ${heading.textContent}`);
  action.setAttribute("aria-pressed", "false");
  heading.append(action);
});

const setBookmarkedHeadings = (headingIDs) => {
  const bookmarked = new Set(Array.isArray(headingIDs) ? headingIDs : []);
  headings.forEach((heading) => {
    const action = heading.querySelector(":scope > .bookmark-heading");
    if (!action) return;
    const isBookmarked = bookmarked.has(heading.id);
    const title = heading.dataset.title || heading.textContent;
    action.classList.toggle("is-bookmarked", isBookmarked);
    action.textContent = isBookmarked ? "★" : "☆";
    action.title = `${isBookmarked ? "Remove bookmark from" : "Bookmark"} ${title}`;
    action.setAttribute(
      "aria-label",
      `${isBookmarked ? "Remove bookmark from" : "Bookmark"} heading ${title}`
    );
    action.setAttribute("aria-pressed", String(isBookmarked));
  });
  return bookmarked.size;
};
state.wordCount = (root.textContent.match(/[\p{Letter}\p{Number}]+/gu) || []).length;

const updateLocation = () => {
  const maximum = Math.max(1, document.documentElement.scrollHeight - window.innerHeight);
  state.verticalOffset = window.scrollY;
  state.progress = Math.max(0, Math.min(1, window.scrollY / maximum));
  const marker = window.scrollY + Math.min(160, window.innerHeight * 0.25);
  state.headingID = headings.filter((heading) => heading.offsetTop <= marker).at(-1)?.id || null;
};
document.addEventListener("scroll", updateLocation, { passive: true });
document.addEventListener("selectionchange", () => {
  state.selectedText = document.getSelection()?.toString().trim().slice(0, 500) || "";
});
updateLocation();

if (window.mermaid && root.querySelector(".mermaid")) {
  window.mermaid.initialize({
    startOnLoad: false,
    securityLevel: "strict",
    theme: bootstrap.mermaidTheme || "neutral",
    fontFamily: "-apple-system, BlinkMacSystemFont, sans-serif"
  });
  window.mermaid.run({ nodes: root.querySelectorAll(".mermaid"), suppressErrors: true }).catch(() => {
    root.querySelectorAll(".mermaid[data-processed]:empty").forEach((node) => {
      node.textContent = "Diagram could not be rendered.";
      node.classList.add("rich-error");
    });
  });
}

let marks = [];
const clearSearch = () => {
  for (const mark of marks) mark.replaceWith(document.createTextNode(mark.textContent));
  root.normalize();
  marks = [];
  state.activeSearchIndex = -1;
  state.searchCount = 0;
  state.activeSearchSection = "";
};

const search = (query) => {
  clearSearch();
  if (!query) return state;
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      return node.parentElement?.closest("script, style, mark, .copy-code") ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT;
    }
  });
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  const needle = query.toLocaleLowerCase();
  for (const node of nodes) {
    const text = node.textContent;
    let start = 0;
    let index = text.toLocaleLowerCase().indexOf(needle, start);
    if (index < 0) continue;
    const fragment = document.createDocumentFragment();
    while (index >= 0) {
      fragment.append(text.slice(start, index));
      const mark = document.createElement("mark");
      mark.className = "search-match";
      mark.textContent = text.slice(index, index + query.length);
      fragment.append(mark);
      marks.push(mark);
      start = index + query.length;
      index = text.toLocaleLowerCase().indexOf(needle, start);
    }
    fragment.append(text.slice(start));
    node.replaceWith(fragment);
  }
  state.searchCount = marks.length;
  if (marks.length) activateSearch(0);
  return state;
};

const activateSearch = (index) => {
  if (!marks.length) return state;
  marks[state.activeSearchIndex]?.classList.remove("active");
  state.activeSearchIndex = (index + marks.length) % marks.length;
  const mark = marks[state.activeSearchIndex];
  mark.classList.add("active");
  mark.scrollIntoView({ block: "center", behavior: bootstrap.reduceMotion ? "instant" : "smooth" });
  state.activeSearchSection = headings.filter((heading) => heading.offsetTop <= mark.offsetTop).at(-1)?.dataset.title || "";
  return state;
};

window.MD22 = Object.freeze({
  state: () => ({ ...state }),
  headings: () => headings.map((heading) => ({
    id: heading.id,
    level: Number(heading.tagName.slice(1)),
    title: heading.dataset.title || heading.textContent
  })),
  navigateTo: (id, emphasize = true) => {
    const target = document.getElementById(id);
    if (!target) return false;
    target.scrollIntoView({ block: "start", behavior: bootstrap.reduceMotion ? "instant" : "smooth" });
    if (emphasize) {
      target.classList.add("arrival-target");
      setTimeout(() => target.classList.remove("arrival-target"), 1500);
    }
    return true;
  },
  restore: (location) => {
    const maximum = Math.max(0, document.documentElement.scrollHeight - window.innerHeight);
    const exactOffset = location?.verticalOffset || maximum * (location?.progress || 0);
    if (exactOffset > 0) {
      window.scrollTo({ top: exactOffset, behavior: "instant" });
    } else if (location?.headingID) {
      window.MD22.navigateTo(location.headingID, false);
    }
  },
  emphasizeLocation: () => {
    const target = document.elementFromPoint(window.innerWidth / 2, Math.min(180, window.innerHeight / 3))
      ?.closest("h1, h2, h3, h4, h5, h6, p, li, blockquote, pre, table") || root;
    target.classList.add("arrival-target");
    setTimeout(() => target.classList.remove("arrival-target"), 1500);
    return true;
  },
  search,
  clearSearch,
  nextSearch: () => activateSearch(state.activeSearchIndex + 1),
  previousSearch: () => activateSearch(state.activeSearchIndex - 1),
  setBookmarkedHeadings,
  waitForExportResources: async () => {
    await document.fonts?.ready;
    const pendingImages = [...document.images]
      .filter((image) => !image.complete)
      .map((image) => new Promise((resolve) => {
        image.addEventListener("load", resolve, { once: true });
        image.addEventListener("error", resolve, { once: true });
      }));
    await Promise.race([
      Promise.all(pendingImages),
      new Promise((resolve) => setTimeout(resolve, 3000))
    ]);
    return true;
  },
  prepareExport: async (themeID) => {
    clearSearch();
    document.documentElement.dataset.theme = themeID || "light";
    document.documentElement.dataset.reduceMotion = "true";
    document.documentElement.dataset.exporting = "true";
    return window.MD22.waitForExportResources();
  },
  exportHTML: (themeID) => {
    const clone = document.documentElement.cloneNode(true);
    clone.dataset.theme = themeID || "light";
    clone.dataset.reduceMotion = "true";
    clone.dataset.exporting = "true";
    delete clone.dataset.ready;
    clone.querySelectorAll("script, .bookmark-heading, .copy-code").forEach((element) => element.remove());
    clone.querySelectorAll("mark.search-match").forEach((mark) => {
      mark.replaceWith(document.createTextNode(mark.textContent || ""));
    });
    clone.querySelectorAll(".arrival-target").forEach((element) => element.classList.remove("arrival-target"));
    return `<!doctype html>\n${clone.outerHTML}`;
  }
});

document.documentElement.dataset.ready = "true";
